### PR TITLE
Crashes track error

### PR DESCRIPTION
**Pull request by hrafnkellbaldurs**
Hey, I hope this helps. I noticed when adding this that the `trackError` functionality is unfortunately not supported by AppCenter for iOS 😦 
https://github.com/microsoft/appcenter/issues/192
I added a stub for iOS in the meantime

* Added trackError plugin method for android
* Added trackError plugin method stub for ios (not currently supported by AppCenter SDK)
* Added trackError to method interface in ts
* Added example for Crashes.trackError

### CODE REVIEW

**Comment by hrafnkellbaldurs** [comment]
It looks like they've added `Crashes.trackError` for iOS in v4.3.0 :rocket: https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.3.0

**Comment by johnborges** [comment]
> It looks like they've added `Crashes.trackError` for iOS in v4.3.0 🚀 https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.3.0

Were you going to work on iOS version in same PR too?

**Comment by hrafnkellbaldurs** [comment]
> > It looks like they've added `Crashes.trackError` for iOS in v4.3.0 🚀 https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.3.0
> 
> Were you going to work on iOS version in same PR too?

Yes I was gonna do it as soon as the version of AppCenter/Core that AppCenterCapacitor is using was updated in https://github.com/johnborges/AppCenterCapacitorShared/pull/4

**Comment by johnborges** [comment]
Ok cool. I merge that PR for `AppCenterCapacitorShared` and published the pod.

**Review by johnborges — APPROVED** [review]

**Comment by hrafnkellbaldurs** [comment]
Hey John, just so you know, I'm still working on the iOS part of `trackError`. 
Were you thinking of merging the branch as is to master?

**Comment by johnborges** [comment]
Yes. I was thinking a separate PR might be good for the iOS piece since this one is growing quite large.

**Pull request merged**
